// Shared facts and locale-specific writing rules: see README.md.
export const content = {
  en: {
    title: "Cat Break — A little company for your break.",
    description: "Cat Break is free on the Mac App Store. Preview version 1.1: choose a cat or three Shiba puppies, set your own break schedule, and see time remaining in the menu bar.",
    skip: "Skip to content",
    navHow: "How it works",
    navSupport: "Support",
    navPrivacy: "Privacy",
    heroTitle: ["Take a break.","With a little company."],
    heroDescription: "An orange cat or three playful Shiba puppies visit your screen. Watch them settle in, give them a pet, and return to work whenever you’re ready.",
    ctaDemo: "See them in action",
    ctaSupport: "Get help",
    releaseNote: "A preview of version 1.1. Animal selection, custom times, and the refreshed interface shown below are coming in the next update. The App Store currently offers version 1.0.",
    ctaStore: "Get version 1.0",
    availability: "Version 1.0 available · macOS 15+ · Free",
    howLabel: "Coming in version 1.1",
    howTitle: ["They arrive.","Your break begins."],
    howIntro: "Choose your companion in Settings → Animal. Your choice applies to the next break. Start a break from the menu bar, or let reminders bring them to you.",
    steps: [
      {"title":"A familiar face. Or three.","body":"The orange cat walks in and settles down. The three Shiba puppies play together before getting sleepy. Optional arrival sounds announce their visit."},
      {"title":"Once they rest, give them a pet.","body":"Select “Pet” when they’re asleep. The bar shows how: slide three fingers on the trackpad without clicking, or click and drag with a mouse over the animal."},
      {"title":"Back to work. Anytime.","body":"“Dismiss” ends the break immediately. “Snooze 10 min” hides your companion and reminds you again in 10 minutes. The bar keeps its layout as you pet."}
    ],
    galleryLabel: "Version 1.1 interface preview",
    galleryAlt: ["An orange cat walking across a fictional work screen.","Version 1.1 preview: a sleeping cat above the transparent break controls, on a fictional work screen.","Version 1.1 preview: the fixed break bar showing three-finger and mouse petting instructions.","Version 1.1 native Animal settings pane, offering the orange cat and three Shiba puppies."],
    galleryNames: ["The cat arrives","Time to rest","Petting guidance","Choose an animal"],
    enlarge: "Enlarge image",
    closeImage: "Close image",
    detailsLabel: "Your preferences",
    detailsTitle: ["Your break.", "Your choice."],
    detailsIntro: "Enter a reminder interval from 1 to 1,440 minutes and a break length from 1 to 60 minutes. The menu bar shows the remaining time. Set quiet hours or pause reminders when you need to focus.",
    features: [
      {"title":"Choose your company.","body":"Open Animal in the native macOS Settings sidebar to choose the orange cat or three Shiba puppies. A change takes effect at your next break, so the current visit can finish."},
      {"title":"Free. Private. No account.","body":"No sign-up, ads, or usage analytics. Your settings, schedule, and break records stay on your Mac and are not sent to the developer’s servers."},
      {"title":"Their sounds, your choice.","body":"Sounds start off. Save separate sound preferences for each animal: an arrival meow or puppy barks, and optional purring while you pet the cat. The puppies do not purr; their petting response is silent."}
    ],
    supportLabel: "Support",
    supportTitle: "A few things to know.",
    supportIntro: "These instructions describe version 1.1, the upcoming update. If you use version 1.0 or need help, send an email.",
    contactLabel: "Email support",
    contactHint: "Tell us your app and macOS versions, Mac model, and whether you use a trackpad or mouse. Describe what you were doing when the problem occurred. Do not send passwords, private documents, or screenshots with personal information.",
    faqs: [
      {"q":"How do I start a break or choose an animal?","a":"Finish the first-run setup, then click the time or status shown in the menu bar to start a break or open Settings. General holds common settings; Animal lets you choose your companion for the next break."},
      {"q":"When will reminders appear?","a":"Enter any whole-number interval from 1 to 1,440 minutes—30, 60, and 120 are examples, not the only choices. Clock-based reminders follow multiples of that interval from midnight. Start-based reminders count from enabling, resuming, or changing the interval. Breaks last 1–60 minutes, counted from when sleep or the still image appears. Quiet hours and pause are optional."},
      {"q":"How do I pet an animal?","a":"Wait until it is asleep, then select “Pet”. Put the pointer over the animal and slide three fingers on the trackpad without clicking, or hold the mouse button and drag. The instructions remain visible while petting is enabled. The puppies react silently; cat purring is optional."},
      {"q":"Why do three fingers switch desktops?","a":"macOS may already use that gesture to switch desktops. Cat Break does not block system gestures or change those settings. Use mouse click-and-drag instead, or check your trackpad gesture settings in macOS."},
      {"q":"Why can’t I hear anything?","a":"Sounds are off by default and saved separately for each animal. In Settings, choose an animal and enable its arrival sound. The cat also has optional purring that builds to your chosen volume while you pet. The puppies have no purring or petting sound."},
      {"q":"How do I get back to work?","a":"Select “Dismiss” to remove the animals immediately. “Snooze 10 min” also hides them and sets a reminder for 10 minutes later. Turn off or pause automatic reminders from the menu bar."},
      {"q":"Can I turn off the animation?","a":"Yes. Turn on “Reduce Motion” in Settings to show a still image instead of video. Cat Break also follows the macOS Reduce Motion setting."},
      {"q":"What are the system and language requirements?","a":"Cat Break requires macOS 15 or later. The app supports English and Korean. It uses the first supported language in your system’s preferred languages, or English if neither is listed. This website also offers Japanese and French; the app does not yet support those languages."},
      {"q":"Where can I download it?","a":"Version 1.0 is available free on the Mac App Store, with no account required by the app. The animal choice, custom times, and interface shown here preview version 1.1 and are not yet in the public version."}
    ],
    privacyLabel: "Privacy",
    privacyTitle: "App data stays on your Mac.",
    privacyLead: "No account, ads, or analytics tools. The app keeps settings and break records on your Mac and does not send them to the developer’s servers. Details about support email and website hosting are below.",
    privacySections: [
      { title: "What the app saves", body: "The app saves your settings and reminder schedule. It also records when breaks start and end, their current state, how they ended, and how long the animal was displayed. These records describe breaks in the app, not your work activity." },
      { title: "How petting works", body: "The app uses your gestures to respond while you pet the animal. It does not save touch paths or keystrokes, take screenshots, or collect document contents, browsing history, microphone audio, or camera images. Information used to return you to your previous app is kept temporarily in memory, not saved to disk." },
      { title: "Deleting app data", body: "There is no button in the app to delete settings or break records yet. For removal instructions, email music.bk@gmail.com. Deleting the app alone may leave some settings and records on your Mac." },
      { title: "Apple services", body: "If you choose to share diagnostics with Apple, Apple’s policies apply. Data handled by the App Store and TestFlight is also covered by Apple’s policies, separately from the data this app stores on your Mac." },
      { title: "Email and this website", body: "When you email support, your contact details and message are used to answer your question and help resolve the issue. To request deletion of that correspondence, email music.bk@gmail.com. This website uses no analytics tools or cookies and does not save preferences in your browser. GitHub Pages hosts the site. Its standard access logs are covered by GitHub’s policies." }
    ],
    footerLine: "A little company for your break.",
    backTop: "Back to top"
  },
  fr: {
    title: "Cat Break — Une pause bien accompagnée.",
    description: "Cat Break est gratuit sur le Mac App Store. Découvrez en avant-première la version 1.1 : choix du chat ou des chiots, durées personnalisées et temps restant dans la barre des menus.",
    skip: "Aller au contenu",
    navHow: "Découvrir",
    navSupport: "Assistance",
    navPrivacy: "Confidentialité",
    heroTitle: ["Une pause.","Bien accompagnée."],
    heroDescription: "Un chat roux ou trois chiots Shiba joueurs apparaissent à l’écran. Regardez-les se reposer, caressez-les et reprenez votre travail quand vous le souhaitez.",
    ctaDemo: "Les découvrir",
    ctaSupport: "Obtenir de l’aide",
    releaseNote: "Aperçu de la version 1.1. Le choix de l’animal, les durées personnalisées et la nouvelle interface présentés ici arriveront dans la prochaine mise à jour. L’App Store propose actuellement la version 1.0.",
    ctaStore: "Obtenir la version 1.0",
    availability: "Version 1.0 disponible · macOS 15+ · Gratuit",
    howLabel: "À venir dans la version 1.1",
    howTitle: ["Ils arrivent.","La pause commence."],
    howIntro: "Choisissez votre compagnon dans les réglages, sous « Animal ». Votre choix prend effet à la prochaine pause. Lancez une pause depuis la barre des menus, ou attendez le rappel.",
    steps: [
      {"title":"Une compagnie. Ou trois.","body":"Le chat roux arrive et s’installe. Les trois chiots Shiba jouent ensemble avant de s’endormir. Activez leur cri d’arrivée si vous souhaitez les entendre avant de les voir."},
      {"title":"Une fois endormis, place aux caresses.","body":"Sélectionnez « Pet » quand ils dorment. La barre affiche les gestes à utiliser : glissez trois doigts sur le trackpad sans cliquer, ou cliquez et faites glisser la souris sur l’animal."},
      {"title":"Reprenez quand vous voulez.","body":"« Dismiss » termine la pause immédiatement. « Snooze 10 min » masque les animaux et vous rappelle de faire une pause 10 minutes plus tard. Les boutons gardent leur place pendant les caresses."}
    ],
    galleryLabel: "Aperçu de l’interface 1.1",
    galleryAlt: ["Un chat roux marche devant un écran de travail fictif.","Aperçu 1.1 : le chat dort au-dessus des commandes de pause transparentes, devant un écran de travail fictif.","Aperçu 1.1 : la barre fixe affiche les instructions pour caresser avec trois doigts ou la souris.","Réglages Animal natifs de la version 1.1, avec le choix du chat roux ou des trois chiots Shiba."],
    galleryNames: ["Le chat arrive","Au repos","Guide des caresses","Choisir un animal"],
    enlarge: "Agrandir l’image",
    closeImage: "Fermer l’image",
    detailsLabel: "Vos réglages",
    detailsTitle: ["Vos pauses.", "À votre rythme."],
    detailsIntro: "Saisissez un intervalle de 1 à 1 440 minutes et une durée de pause de 1 à 60 minutes. Le temps restant apparaît dans la barre des menus. Définissez des plages sans rappels, ou suspendez-les.",
    features: [
      {"title":"Choisissez votre compagnie.","body":"Dans les réglages macOS natifs, ouvrez « Animal » pour choisir le chat roux ou les trois chiots Shiba. Le changement s’applique à la prochaine pause ; la visite en cours se termine avec le même animal."},
      {"title":"Gratuit, sans compte et sans suivi.","body":"Ni publicité ni outil d’analyse de votre utilisation. Vos réglages, horaires et historiques de pauses restent sur votre Mac, sans être envoyés aux serveurs du développeur."},
      {"title":"À chacun ses sons.","body":"Les sons sont désactivés au départ. Réglez séparément le miaulement et les aboiements d’arrivée. Le chat peut aussi ronronner pendant les caresses. La réaction des chiots aux caresses est silencieuse ; ils ne ronronnent pas."}
    ],
    supportLabel: "Assistance",
    supportTitle: "Les réponses à vos questions.",
    supportIntro: "Ces instructions concernent la prochaine version, 1.1. Vous utilisez la version 1.0 ou avez besoin d’aide ? Écrivez-nous.",
    contactLabel: "Contacter l’assistance",
    contactHint: "Indiquez les versions de l’application et de macOS, le modèle de Mac et si vous utilisez un trackpad ou une souris. Décrivez ce que vous faisiez au moment du problème. N’envoyez pas de mot de passe, de document privé ni de capture contenant des informations personnelles.",
    faqs: [
      {"q":"Comment lancer une pause ou choisir un animal ?","a":"Terminez la configuration initiale, puis cliquez sur le temps ou l’état affiché dans la barre des menus pour lancer une pause ou ouvrir les réglages. « General » contient les réglages courants ; « Animal », juste en dessous, permet de choisir le compagnon de la prochaine pause."},
      {"q":"Quand les rappels apparaissent-ils ?","a":"Saisissez un nombre entier de 1 à 1 440 minutes. 30, 60 et 120 minutes ne sont que des exemples. Le mode basé sur l’horloge suit les multiples de cet intervalle depuis minuit. L’autre mode compte depuis l’activation, la reprise ou le changement d’intervalle. Une pause dure de 1 à 60 minutes, à partir de l’affichage du sommeil ou de l’image fixe. Vous pouvez définir des plages sans rappels ou les suspendre."},
      {"q":"Comment caresser un animal ?","a":"Attendez qu’il dorme et sélectionnez « Pet ». Placez le pointeur sur l’animal et glissez trois doigts sur le trackpad sans cliquer, ou maintenez le bouton de la souris enfoncé et faites glisser. Les instructions restent visibles tant que les caresses sont activées. Les chiots réagissent en silence ; le ronronnement du chat est facultatif."},
      {"q":"Pourquoi le geste à trois doigts change-t-il de bureau ?","a":"macOS peut déjà utiliser ce geste pour changer de bureau. Cat Break ne bloque pas les gestes du système et ne modifie pas ces réglages. Utilisez la souris en maintenant le bouton enfoncé, ou vérifiez les réglages des gestes du trackpad dans macOS."},
      {"q":"Pourquoi n’y a-t-il pas de son ?","a":"Les sons sont désactivés au départ et les préférences sont enregistrées par animal. Choisissez un animal dans les réglages et activez son cri d’arrivée. Le chat peut aussi ronronner pendant les caresses, avec un volume qui augmente jusqu’au niveau choisi. Les chiots ne ronronnent pas et leur réaction aux caresses reste silencieuse."},
      {"q":"Comment reprendre mon travail ?","a":"« Dismiss » fait disparaître les animaux immédiatement. « Snooze 10 min » les masque et programme un rappel 10 minutes plus tard. Vous pouvez désactiver ou suspendre les rappels automatiques depuis la barre des menus."},
      {"q":"Puis-je désactiver l’animation ?","a":"Oui. Activez « Reduce Motion » dans les réglages pour afficher une image fixe à la place de la vidéo. Cat Break suit également le réglage de réduction des animations de macOS."},
      {"q":"Quels sont les Mac et les langues compatibles ?","a":"Cat Break nécessite macOS 15 ou une version ultérieure. L’application propose l’anglais et le coréen. Elle choisit la première de ces langues dans les langues préférées du système, ou l’anglais si aucune n’y figure. Ce site propose aussi le français et le japonais, mais l’application ne prend pas encore ces deux langues en charge."},
      {"q":"Où télécharger l’application ?","a":"La version 1.0 est gratuite sur le Mac App Store. L’app ne nécessite pas de compte. Le choix de l’animal, les durées personnalisées et la nouvelle interface présentés ici sont un aperçu de la version 1.1 et ne sont pas encore inclus dans la version publique."}
    ],
    privacyLabel: "Confidentialité",
    privacyTitle: "Les données de l’app restent sur votre Mac.",
    privacyLead: "Pas de compte, de publicité ni d’outil d’analyse. L’application conserve vos réglages et l’historique des pauses sur votre Mac, sans les envoyer aux serveurs du développeur. Les informations sur les e-mails et l’hébergement du site figurent ci-dessous.",
    privacySections: [
      { title: "Ce que l’application enregistre", body: "L’application enregistre vos réglages et les horaires des rappels. Elle conserve aussi les heures de début et de fin des pauses, leur état, la façon dont elles se terminent et la durée d’affichage des animaux. Ces données concernent les pauses dans l’application, pas votre activité professionnelle." },
      { title: "Les gestes de caresse", body: "L’application traite vos gestes pour réagir pendant les caresses. Elle n’enregistre ni les trajectoires des doigts ni les frappes au clavier et ne capture pas l’écran. Elle ne collecte pas le contenu des documents, l’historique de navigation, le son du microphone ni les images de la caméra. Les informations permettant de revenir à l’application précédente restent temporairement en mémoire et ne sont pas enregistrées sur disque." },
      { title: "Supprimer les données de l’application", body: "L’application ne propose pas encore de bouton pour supprimer les réglages ou l’historique des pauses. Pour savoir comment les supprimer, écrivez à music.bk@gmail.com. Supprimer l’application peut laisser certains réglages et enregistrements sur votre Mac." },
      { title: "Les services Apple", body: "Si vous choisissez de partager des diagnostics avec Apple, les politiques d’Apple s’appliquent. Elles couvrent aussi les données traitées par l’App Store et TestFlight, séparément des données que cette application conserve sur votre Mac." },
      { title: "Les e-mails et ce site", body: "Lorsque vous écrivez à l’assistance, vos coordonnées et votre message servent à vous répondre et à résoudre le problème. Vous pouvez demander la suppression de ces échanges à music.bk@gmail.com. Ce site n’utilise ni outil d’analyse ni cookie et n’enregistre pas vos préférences dans le navigateur. Il est hébergé sur GitHub Pages. Les journaux d’accès habituels de l’hébergeur relèvent des politiques de GitHub." }
    ],
    footerLine: "Une pause bien accompagnée.",
    backTop: "Haut de page"
  },
  ko: {
    title: "Cat Break — 함께 잠깐 쉬어 가세요.",
    description: "Cat Break는 Mac App Store에서 무료로 받을 수 있어요. 다음 1.1 업데이트의 동물 선택, 직접 시간 입력, 메뉴 막대 남은 시간과 새 화면을 미리 만나보세요.",
    skip: "본문으로 건너뛰기",
    navHow: "사용 방법",
    navSupport: "지원",
    navPrivacy: "개인정보 보호",
    heroTitle: ["함께,","잠깐 쉬어 가세요."],
    heroDescription: "주황 고양이 또는 장난꾸러기 시바견 강아지 세 마리가 화면에 찾아와요. 쉬는 모습을 지켜보고 쓰다듬어 주세요. 원할 때 언제든 작업으로 돌아갈 수 있어요.",
    ctaDemo: "만나보기",
    ctaSupport: "도움 받기",
    releaseNote: "1.1 버전을 미리 소개해요. 아래 동물 선택·시간 직접 입력·새 화면은 다음 업데이트에 포함될 기능이에요. 현재 App Store에서는 1.0 버전을 받을 수 있어요.",
    ctaStore: "1.0 버전 다운로드",
    availability: "1.0 버전 다운로드 가능 · macOS 15+ · 무료",
    howLabel: "다음 1.1 업데이트",
    howTitle: ["친구들이 오면,","잠깐 쉬어 갈 시간."],
    howIntro: "설정의 ‘동물’에서 함께 쉴 친구를 골라주세요. 다음 휴식부터 찾아와요. 메뉴 막대에서 바로 휴식을 시작하거나 알림 시간을 정할 수 있어요.",
    steps: [
      {"title":"한 마리, 또는 세 마리.","body":"주황 고양이는 걸어와 편히 자리를 잡아요. 시바견 강아지 세 마리는 함께 장난치다가 졸기 시작해요. 등장 소리를 켜면 찾아오기 전에 알려줘요."},
      {"title":"잠들면 쓰다듬어 보세요.","body":"잠든 뒤 ‘쓰다듬기’를 누르면 아래에 사용법이 계속 보여요. 동물 위에서 클릭 없이 트랙패드를 세 손가락으로 쓸거나, 마우스 버튼을 누른 채 움직여주세요."},
      {"title":"돌아가고 싶을 땐, 바로.","body":"‘닫기’를 누르면 바로 휴식을 마쳐요. ‘10분 미루기’를 누르면 동물들이 사라지고 10분 뒤에 다시 알려줘요. 쓰다듬는 동안에도 버튼 위치는 그대로예요."}
    ],
    galleryLabel: "1.1 버전 화면 미리보기",
    galleryAlt: ["예시 업무 화면 위로 걸어오는 주황 고양이.","1.1 미리보기: 예시 업무 화면 위에 잠든 고양이와 투명한 휴식 조작 막대.","1.1 미리보기: 위치가 고정된 휴식 막대에 세 손가락과 마우스 쓰다듬기 안내가 표시된 모습.","1.1 기본 macOS 동물 설정 화면에서 주황 고양이와 시바견 강아지 세 마리를 고르는 모습."],
    galleryNames: ["고양이 등장","휴식 시간","쓰다듬기 안내","동물 선택"],
    enlarge: "이미지 크게 보기",
    closeImage: "이미지 닫기",
    detailsLabel: "원하는 대로 설정",
    detailsTitle: ["쉬는 시간도,", "내 방식대로."],
    detailsIntro: "알림 간격은 1~1,440분, 휴식 시간은 1~60분 사이에서 직접 입력해요. 메뉴 막대에서 남은 시간을 확인하고, 집중할 때는 제외 시간을 정하거나 알림을 잠시 꺼 두세요.",
    features: [
      {"title":"함께 쉴 친구를 골라요.","body":"macOS 기본 형태의 설정 창에서 ‘동물’을 열어 주황 고양이나 시바견 강아지 세 마리를 선택해요. 진행 중인 휴식은 그대로 마치고 다음 휴식부터 새 선택을 적용해요."},
      {"title":"무료로, 가입 없이.","body":"광고나 사용 내역 추적 도구가 없어요. 설정과 알림 일정, 휴식 기록은 Mac에 저장하며 개발자 서버로 보내지 않아요."},
      {"title":"동물마다 소리도 따로.","body":"소리는 처음에는 꺼져 있어요. 고양이의 야옹 소리와 강아지의 짖는 소리를 각각 설정할 수 있어요. 고양이를 쓰다듬을 때 골골 소리를 켤 수도 있어요. 강아지의 쓰다듬기 반응은 무음이며 골골 소리는 없어요."}
    ],
    supportLabel: "지원",
    supportTitle: "궁금한 점이 있나요?",
    supportIntro: "아래 사용법은 다음 업데이트인 1.1 기준이에요. 1.0을 사용 중이거나 도움이 필요하면 이메일로 문의해 주세요.",
    contactLabel: "이메일로 문의하기",
    contactHint: "앱과 macOS 버전, Mac 모델, 트랙패드와 마우스 중 무엇을 쓰는지 알려주세요. 문제가 생겼을 때 어떤 조작을 했는지도 적어주세요. 비밀번호, 개인 문서, 개인정보가 담긴 화면 캡처는 보내지 마세요.",
    faqs: [
      {"q":"휴식을 시작하거나 동물을 바꾸려면 어떻게 하나요?","a":"첫 실행 안내를 마치고 메뉴 막대의 시간 또는 상태 표시를 누르면 휴식을 시작하거나 설정을 열 수 있어요. ‘일반’에서 기본 설정을, 그 아래 ‘동물’에서 다음 휴식에 만날 친구를 정해요."},
      {"q":"알림은 언제 오나요?","a":"1~1,440분 사이의 정수를 입력해요. 30분, 60분, 120분 외에 원하는 간격도 사용할 수 있어요. ‘시계 기준’은 그날 0시부터 간격의 배수에 맞추고, ‘시작 기준’은 알림 시작·재개·간격 변경 시점부터 계산해요. 휴식 시간은 1~60분이며 수면 영상이나 정지 이미지가 보일 때부터 세어요. 제외 시간이나 일시 정지도 설정할 수 있어요."},
      {"q":"동물을 어떻게 쓰다듬나요?","a":"잠들면 ‘쓰다듬기’를 눌러주세요. 동물 위에 커서를 놓고 클릭 없이 트랙패드를 세 손가락으로 쓸거나, 마우스 버튼을 누른 채 움직여요. 쓰다듬기가 켜져 있는 동안 사용법이 계속 보여요. 강아지는 소리 없이 반응하고, 고양이의 골골 소리는 선택할 수 있어요."},
      {"q":"세 손가락으로 쓸면 다른 데스크탑으로 넘어가요.","a":"macOS에 같은 동작이 데스크탑 전환으로 설정되어 있을 수 있어요. Cat Break는 시스템 동작을 막거나 설정을 바꾸지 않아요. 마우스 버튼을 누른 채 움직이는 방법을 쓰거나, macOS의 트랙패드 제스처 설정을 확인해 주세요."},
      {"q":"소리가 들리지 않아요.","a":"소리는 기본으로 꺼져 있고 동물마다 따로 저장해요. 설정에서 동물을 선택한 뒤 등장 소리를 켜주세요. 고양이는 쓰다듬을 때 정해둔 음량까지 커지는 골골 소리도 켤 수 있어요. 강아지에는 골골 소리나 쓰다듬기 반응음이 없어요."},
      {"q":"작업으로 돌아가려면 어떻게 하나요?","a":"‘닫기’를 누르면 동물들이 바로 사라져요. ‘10분 미루기’를 누르면 사라졌다가 10분 뒤에 다시 알려줘요. 메뉴 막대에서 자동 알림을 끄거나 잠시 멈출 수도 있어요."},
      {"q":"동물이 움직이지 않게 할 수 있나요?","a":"네. 설정에서 ‘움직임 줄이기’를 켜면 영상 대신 정지 이미지로 보여줘요. macOS의 ‘움직임 줄이기’ 설정도 따라요."},
      {"q":"어떤 환경에서 사용할 수 있나요?","a":"macOS 15 이상이 필요해요. 앱은 영어와 한국어를 지원하며, 시스템의 선호 언어 순서에 따라 둘 중 하나를 사용해요. 두 언어가 모두 없으면 영어로 표시해요. 웹사이트는 일본어와 프랑스어도 제공하지만, 앱은 아직 두 언어를 지원하지 않아요."},
      {"q":"어디서 다운로드할 수 있나요?","a":"Mac App Store에서 1.0 버전을 무료로 받을 수 있어요. 앱에서 계정을 만들 필요는 없어요. 이 페이지의 동물 선택·시간 직접 입력·새 화면은 다음 1.1 업데이트 미리보기이며 아직 공개 버전에 포함되어 있지 않아요."}
    ],
    privacyLabel: "개인정보 보호",
    privacyTitle: "앱 기록은 Mac 안에.",
    privacyLead: "계정도, 광고도, 분석 도구도 없어요. 앱은 설정과 휴식 기록을 Mac에 저장하고 개발자 서버로 보내지 않아요. 지원 이메일과 웹사이트에서 정보를 다루는 방식은 아래에 안내해요.",
    privacySections: [
      { title: "앱에 저장되는 정보", body: "설정과 알림 일정을 저장해요. 휴식을 시작하고 마친 시각, 진행 상태, 어떻게 종료했는지, 동물이 표시된 시간도 기록해요. 앱에서의 휴식에 관한 기록이며, 작업 내용을 추적하는 정보는 아니에요." },
      { title: "쓰다듬을 때 사용하는 정보", body: "동물이 쓰다듬기에 반응하도록 손가락과 마우스 움직임을 일시적으로 처리해요. 손가락이 움직인 경로나 누른 키는 저장하지 않고, 화면을 캡처하지도 않아요. 문서 내용, 웹 방문 내역, 마이크 소리, 카메라 이미지도 수집하지 않아요. 이전 앱으로 돌아가기 위한 정보는 메모리에 잠시 보관하며 파일로 저장하지 않아요." },
      { title: "앱 데이터 삭제", body: "현재 앱에는 설정이나 휴식 기록을 삭제하는 버튼이 없어요. 삭제 방법은 music.bk@gmail.com으로 문의해 주세요. 앱만 지우면 일부 설정과 기록이 Mac에 남을 수 있어요." },
      { title: "Apple 서비스", body: "Apple에 진단 정보를 공유하도록 선택한 경우에는 Apple의 정책이 적용돼요. App Store와 TestFlight가 처리하는 정보에도 Apple의 정책이 적용돼요. 이는 이 앱이 Mac에 저장하는 정보와는 별개예요." },
      { title: "이메일과 웹사이트", body: "이메일로 보내주신 연락처와 문의 내용은 답변과 문제 해결에 사용해요. 문의 내역 삭제는 music.bk@gmail.com으로 요청할 수 있어요. 이 웹사이트는 분석 도구나 쿠키를 사용하지 않고, 브라우저에 환경설정을 저장하지 않아요. 사이트는 GitHub Pages에서 제공해요. 서비스 운영 과정에서 남는 기본 접속 기록에는 GitHub의 정책이 적용돼요." }
    ],
    footerLine: "함께 잠깐 쉬어 가세요.",
    backTop: "맨 위로"
  },
  ja: {
    title: "Cat Break — 一緒に、ひと休み。",
    description: "Cat BreakはMac App Storeで無料配信中です。次のバージョン1.1の動物選択、時間の直接入力、メニューバーの残り時間表示と新しい画面をご紹介します。",
    skip: "本文へスキップ",
    navHow: "使い方",
    navSupport: "サポート",
    navPrivacy: "プライバシー",
    heroTitle: ["一緒に、","ひと休み。"],
    heroDescription: "茶トラの猫か、遊ぶのが大好きな3匹の柴犬の子犬が画面にやってきます。くつろぐ姿を眺めたり、なでたり。いつでも作業に戻れます。",
    ctaDemo: "様子を見る",
    ctaSupport: "ヘルプを見る",
    releaseNote: "バージョン1.1のプレビューです。以下の動物選択、時間の直接入力、新しい画面は次のアップデートで登場します。現在App Storeではバージョン1.0を配信しています。",
    ctaStore: "バージョン1.0を入手",
    availability: "バージョン1.0を配信中 · macOS 15+ · 無料",
    howLabel: "次のバージョン1.1で",
    howTitle: ["みんなが来たら、","休憩の時間。"],
    howIntro: "設定の「Animal」で一緒に休む相手を選びます。変更は次の休憩から。メニューバーからすぐに始めることも、通知に任せることもできます。",
    steps: [
      {"title":"1匹でも、3匹でも。","body":"茶トラの猫は歩いてきて、落ち着く場所を見つけます。3匹の柴犬の子犬は一緒に遊んでから眠くなります。登場を知らせる鳴き声は、お好みでオンにできます。"},
      {"title":"眠ったら、なでてみよう。","body":"眠ってから「Pet」を選ぶと、操作方法がバーに表示されます。動物の上でクリックせずにトラックパッドを3本指でなでるか、マウスのボタンを押したまま動かします。"},
      {"title":"いつでも作業へ。","body":"「Dismiss」ですぐに休憩を終えられます。「Snooze 10 min」なら動物が消え、10分後にもう一度知らせます。なでている間もボタンの位置は変わりません。"}
    ],
    galleryLabel: "バージョン1.1の画面プレビュー",
    galleryAlt: ["架空の作業画面の上を歩く茶トラの猫。","1.1プレビュー：架空の作業画面に眠る猫と透明な休憩操作バー。","1.1プレビュー：位置が固定されたバーに3本指とマウスでのなで方が表示された画面。","1.1のmacOS標準のAnimal設定画面で、茶トラの猫と3匹の柴犬の子犬を選ぶ様子。"],
    galleryNames: ["猫が登場","休憩の時間","なで方の案内","動物を選ぶ"],
    enlarge: "画像を拡大",
    closeImage: "画像を閉じる",
    detailsLabel: "お好みの設定で",
    detailsTitle: ["休み方も、", "自分らしく。"],
    detailsIntro: "通知間隔は1〜1,440分、休憩時間は1〜60分で直接入力できます。残り時間はメニューバーに表示。集中したい時は通知しない時間帯を決めたり、一時停止したりできます。",
    features: [
      {"title":"一緒に休む相手を選ぶ。","body":"macOS標準の設定画面の「Animal」で、茶トラの猫か3匹の柴犬の子犬を選びます。変更は次の休憩から適用され、進行中の休憩はそのまま終わります。"},
      {"title":"無料。アカウントも不要。","body":"広告や利用状況の解析ツールはありません。設定、通知のスケジュール、休憩の記録はMacに保存し、開発者のサーバーには送りません。"},
      {"title":"音も、それぞれに。","body":"音は最初はオフです。猫と子犬の登場時の鳴き声を個別に設定できます。猫には、なでる時のゴロゴロ音もあります。子犬のなでる反応は無音で、ゴロゴロ音はありません。"}
    ],
    supportLabel: "サポート",
    supportTitle: "気になることは、こちら。",
    supportIntro: "以下は次のアップデート、バージョン1.1の使い方です。1.0をご利用の方や、お困りの方はメールでお問い合わせください。",
    contactLabel: "メールで問い合わせる",
    contactHint: "アプリとmacOSのバージョン、Macのモデル、トラックパッドとマウスのどちらを使っているかをお知らせください。問題が起きた時の操作もご記入ください。パスワード、個人の文書、個人情報を含むスクリーンショットは送らないでください。",
    faqs: [
      {"q":"休憩を始めるには？ 動物を選ぶには？","a":"初回起動時の設定を済ませ、メニューバーの時間や状態の表示をクリックすると、休憩を始めたり設定を開いたりできます。「General」に基本設定があり、その下の「Animal」で次の休憩の相手を選べます。"},
      {"q":"通知はいつ届きますか？","a":"1〜1,440分の整数を入力します。30分、60分、120分以外の間隔も使えます。時刻基準では、その日の0時から間隔の倍数で通知します。開始基準では、通知の有効化・再開・間隔変更から計算します。休憩は1〜60分で、眠る動画または静止画が表示されてから数えます。通知しない時間帯や一時停止も設定できます。"},
      {"q":"動物をなでるには？","a":"眠ったら「Pet」を選びます。ポインタを動物の上に置き、クリックせずにトラックパッドを3本指でなでるか、マウスのボタンを押したまま動かします。有効な間は操作方法が表示されます。子犬は無音で反応し、猫のゴロゴロ音はお好みでオンにできます。"},
      {"q":"3本指でなでるとデスクトップが切り替わります。","a":"macOSで同じジェスチャがデスクトップの切り替えに設定されている場合があります。Cat Breakはシステムのジェスチャを止めたり、設定を変更したりしません。マウスのボタンを押したまま動かす方法を使うか、macOSのトラックパッド設定を確認してください。"},
      {"q":"音が聞こえません。","a":"音は最初はオフで、動物ごとに設定が保存されます。設定で動物を選び、登場時の鳴き声をオンにしてください。猫は、なでると設定した音量まで徐々に大きくなるゴロゴロ音も使えます。子犬にはゴロゴロ音やなでる時の音はありません。"},
      {"q":"作業に戻るには？","a":"「Dismiss」で動物がすぐに消えます。「Snooze 10 min」でも消え、10分後にもう一度知らせます。メニューバーから自動通知をオフにしたり、一時停止したりできます。"},
      {"q":"アニメーションをオフにできますか？","a":"はい。設定の「Reduce Motion」をオンにすると、動画の代わりに静止画を表示します。macOSの「視差効果を減らす」設定にも従います。"},
      {"q":"対応する環境と言語は？","a":"macOS 15以降が必要です。アプリは英語と韓国語に対応しています。システムの優先言語の順に、対応する言語を使います。どちらもない場合は英語で表示します。このウェブサイトには日本語とフランス語もありますが、アプリはまだこの2言語に対応していません。"},
      {"q":"どこでダウンロードできますか？","a":"Mac App Storeでバージョン1.0を無料で配信しています。アプリ用のアカウントは不要です。このページの動物選択、時間の直接入力、新しい画面は次の1.1のプレビューで、公開中のバージョンにはまだ含まれていません。"}
    ],
    privacyLabel: "プライバシー",
    privacyTitle: "設定と休憩の記録は、Macに保存。",
    privacyLead: "アカウントも、広告も、解析ツールもありません。設定と休憩の記録はMacに保存し、開発者のサーバーには送りません。メールとウェブサイトでの情報の取り扱いは、以下をご確認ください。",
    privacySections: [
      { title: "アプリが保存する情報", body: "設定と通知のスケジュールを保存します。休憩を始めた時刻と終えた時刻、進行状況、終了の仕方、動物が表示されていた時間も記録します。アプリ内の休憩の記録であり、作業内容を追跡するものではありません。" },
      { title: "なでる時に使う情報", body: "動物が反応するために、操作を一時的に処理します。指の動いた軌跡やキー入力は保存せず、画面も撮影しません。文書の内容、閲覧履歴、マイクの音声、カメラの画像も収集しません。前のアプリに戻るための情報は一時的にメモリに保持し、ディスクには保存しません。" },
      { title: "アプリのデータを削除するには", body: "現在、設定や休憩の記録を削除するボタンはありません。削除方法はmusic.bk@gmail.comまでお問い合わせください。アプリを削除するだけでは、一部の設定や記録がMacに残る場合があります。" },
      { title: "Appleのサービス", body: "Appleへの診断情報の共有を選んだ場合は、Appleのポリシーが適用されます。App StoreとTestFlightが扱う情報にもAppleのポリシーが適用されます。これらは、このアプリがMacに保存する情報とは別のものです。" },
      { title: "メールとウェブサイト", body: "メールでいただいた連絡先とお問い合わせ内容は、返信と問題解決に使います。メールのやり取りの削除はmusic.bk@gmail.comまでご依頼ください。このウェブサイトは解析ツールやCookieを使わず、ブラウザに設定を保存しません。サイトはGitHub Pagesで提供しています。サービス運営に伴う標準的なアクセス記録には、GitHubのポリシーが適用されます。" }
    ],
    footerLine: "一緒に、ひと休み。",
    backTop: "ページの先頭へ"
  }
};
