// Shared facts and locale-specific writing rules: see README.md.
export const content = {
  en: {
    title: "Cat Break — Take a break with a cat.",
    description: "A cat walks onto your screen when it’s time for a break. Set reminders, pet the cat, and get back to work whenever you’re ready. Coming to the Mac App Store.",
    skip: "Skip to content",
    navHow: "How it works",
    navSupport: "Support",
    navPrivacy: "Privacy",
    heroTitle: ["Take a break.", "With a cat."],
    heroDescription: "When it’s time for a break, a cat walks onto your screen. Watch it settle in. Or get back to work whenever you need to.",
    ctaDemo: "Meet the cat",
    ctaSupport: "Get help",
    availability: "Coming to the Mac App Store · macOS 15+ · Free",
    howLabel: "How it works",
    howTitle: ["A cat arrives.", "Your break begins."],
    howIntro: "Choose when the cat appears, or start a break from the menu bar. Stay for a moment or close it whenever you’re ready.",
    steps: [
      { title: "Here comes the cat.", body: "An orange cat walks in from the edge of your screen. Turn on the meow to hear it just before the cat arrives." },
      { title: "Settle in. Give it a pet.", body: "The cat sits, lies down, and falls asleep. Once it’s asleep, select “Pet the cat” to start petting." },
      { title: "Back to work. Anytime.", body: "Select “Dismiss” to remove the cat straight away. Need a little longer before your break? “Snooze 10 min” hides the cat and reminds you again in 10 minutes." }
    ],
    galleryLabel: "Four cat scenes",
    galleryAlt: [
      "An orange cat walking across a sample work screen.",
      "An orange cat sitting in front of a sample work screen.",
      "An orange cat lying down in front of a sample work screen.",
      "An orange cat sleeping in front of a sample work screen."
    ],
    galleryNames: ["Walking in", "Sitting", "Lying down", "Sleeping"],
    enlarge: "Enlarge image",
    closeImage: "Close image",
    detailsLabel: "Your preferences",
    detailsTitle: ["Your break.", "Your choice."],
    detailsIntro: "Set reminders every 30, 60, or 120 minutes. Choose times when reminders stay off, or pause them when you need to focus.",
    features: [
      { title: "Stored on your Mac.", body: "Your settings, reminder schedule, and break records stay on your Mac. The app does not send them to the developer’s servers." },
      { title: "Free. No account needed.", body: "No sign-up and no ads. The app does not use analytics tools to track how you use it." },
      { title: "Sound is up to you.", body: "Meows and purring are off by default. Turn them on separately and set each volume. As you pet, the purr builds to your chosen volume and continues while you keep petting." }
    ],
    supportLabel: "Support",
    supportTitle: "A few things to know.",
    supportIntro: "Find answers below. If you still need help, send an email.",
    contactLabel: "Email support",
    contactHint: "Tell us your app and macOS versions, Mac model, and whether you use a trackpad or mouse. Describe what you were doing when the problem occurred. Do not send passwords, private documents, or screenshots with personal information.",
    faqs: [
      { q: "How do I start a break?", a: "Complete the setup shown when you first open the app. Then click the paw icon in the menu bar to start a break or open Settings." },
      { q: "When will reminders appear?", a: "Choose a 30-, 60-, or 120-minute interval. Reminders can follow the clock: with a 30-minute interval, they appear at 10:00, 10:30, and so on. Or count the interval from when you turn reminders on or resume them after a pause. You can also set times when reminders stay off." },
      { q: "How do I pet the cat?", a: "Wait until the cat is asleep, then select “Pet the cat”. Place the pointer over the cat and slide three fingers across the trackpad without clicking. With a mouse, hold down the button and drag over the cat." },
      { q: "Why do three fingers switch desktops?", a: "macOS may already use that gesture to switch desktops. Cat Break does not block system gestures or change those settings. Use mouse click-and-drag instead, or check your trackpad gesture settings in macOS." },
      { q: "Why can’t I hear anything?", a: "Sounds are off by default. Open Settings, turn on meows or purring, and raise the volume. Purring starts when you pet the sleeping cat, builds to the volume you set, and continues while you keep petting." },
      { q: "How do I get back to work?", a: "Select “Dismiss” to remove the cat immediately. “Snooze 10 min” also removes it and sets a reminder for 10 minutes later. You can turn automatic reminders off or pause them from the menu bar." },
      { q: "Can I turn off the animation?", a: "Yes. Turn on “Reduce Motion” in Settings to show a still image instead of video. Cat Break also follows the macOS Reduce Motion setting." },
      { q: "What are the system and language requirements?", a: "Cat Break requires macOS 15 or later. The app supports English and Korean. It uses the first supported language in your system’s preferred languages, or English if neither is listed. This website also offers Japanese and French; the app does not yet support those languages." },
      { q: "Where can I download it?", a: "Cat Break is not publicly available yet. It is being prepared for the Mac App Store as a free app with no account required." }
    ],
    privacyLabel: "Privacy",
    privacyTitle: "App data stays on your Mac.",
    privacyLead: "No account, ads, or analytics tools. The app keeps settings and break records on your Mac and does not send them to the developer’s servers. Details about support email and website hosting are below.",
    privacySections: [
      { title: "What the app saves", body: "The app saves your settings and reminder schedule. It also records when breaks start and end, their current state, how they ended, and how long the cat was displayed. These records describe breaks in the app, not your work activity." },
      { title: "How petting works", body: "The app uses your gestures to respond while you pet the cat. It does not save touch paths or keystrokes, take screenshots, or collect document contents, browsing history, microphone audio, or camera images. Information used to return you to your previous app is kept temporarily in memory, not saved to disk." },
      { title: "Deleting app data", body: "There is no button in the app to delete settings or break records yet. For removal instructions, email music.bk@gmail.com. Deleting the app alone may leave some settings and records on your Mac." },
      { title: "Apple services", body: "If you choose to share diagnostics with Apple, Apple’s policies apply. Data handled by the App Store and TestFlight is also covered by Apple’s policies, separately from the data this app stores on your Mac." },
      { title: "Email and this website", body: "When you email support, your contact details and message are used to answer your question and help resolve the issue. To request deletion of that correspondence, email music.bk@gmail.com. This website uses no analytics tools or cookies and does not save preferences in your browser. GitHub Pages hosts the site. Its standard access logs are covered by GitHub’s policies." }
    ],
    footerLine: "Take a break with a cat.",
    backTop: "Back to top"
  },
  fr: {
    title: "Cat Break — Faites une pause avec un chat.",
    description: "Un chat apparaît à l’écran pour vous rappeler de faire une pause. Réglez les rappels, caressez-le et reprenez votre travail quand vous le souhaitez. Bientôt sur le Mac App Store.",
    skip: "Aller au contenu",
    navHow: "Découvrir",
    navSupport: "Assistance",
    navPrivacy: "Confidentialité",
    heroTitle: ["Une pause.", "Avec un chat."],
    heroDescription: "À l’heure de la pause, un chat apparaît à l’écran. Regardez-le s’installer. Vous avez du travail ? Vous pouvez reprendre à tout moment.",
    ctaDemo: "Voir le chat",
    ctaSupport: "Obtenir de l’aide",
    availability: "Bientôt sur le Mac App Store · macOS 15+ · Gratuit",
    howLabel: "Comment ça marche",
    howTitle: ["Le chat arrive.", "La pause commence."],
    howIntro: "Choisissez quand le chat apparaît, ou lancez une pause depuis la barre des menus. Restez un moment avec lui, puis reprenez votre travail quand vous le souhaitez.",
    steps: [
      { title: "Le voilà.", body: "Un chat roux entre par le bord de l’écran. Activez le miaulement pour l’entendre juste avant son arrivée." },
      { title: "Place aux caresses.", body: "Le chat s’assoit, s’allonge et s’endort. Une fois qu’il dort, sélectionnez « Pet the cat » pour le caresser." },
      { title: "Reprenez quand vous voulez.", body: "Sélectionnez « Dismiss » pour faire disparaître le chat immédiatement. Avec « Snooze 10 min », il disparaît et le rappel revient 10 minutes plus tard." }
    ],
    galleryLabel: "Quatre scènes avec le chat",
    galleryAlt: [
      "Un chat roux marche devant un exemple d’écran de travail.",
      "Un chat roux est assis devant un exemple d’écran de travail.",
      "Un chat roux s’allonge devant un exemple d’écran de travail.",
      "Un chat roux dort devant un exemple d’écran de travail."
    ],
    galleryNames: ["Il arrive", "Il s’assoit", "Il s’allonge", "Il dort"],
    enlarge: "Agrandir l’image",
    closeImage: "Fermer l’image",
    detailsLabel: "Vos réglages",
    detailsTitle: ["Vos pauses.", "À votre rythme."],
    detailsIntro: "Choisissez un rappel toutes les 30, 60 ou 120 minutes. Définissez des plages sans rappels, ou suspendez-les pour vous concentrer.",
    features: [
      { title: "Les données de l’app restent sur votre Mac.", body: "L’application conserve vos réglages, les horaires des rappels et l’historique des pauses sur votre Mac. Elle ne les envoie pas aux serveurs du développeur." },
      { title: "Gratuit. Sans compte.", body: "Pas d’inscription ni de publicité. L’application n’utilise aucun outil d’analyse pour suivre votre utilisation." },
      { title: "Le son, à vous de choisir.", body: "Les miaulements et les ronronnements sont désactivés au départ. Activez-les séparément et réglez leur volume. Le volume du ronronnement augmente progressivement jusqu’au niveau choisi et continue tant que vous caressez le chat." }
    ],
    supportLabel: "Assistance",
    supportTitle: "Les réponses à vos questions.",
    supportIntro: "Consultez les réponses ci-dessous. Besoin d’aide ? Écrivez-nous.",
    contactLabel: "Contacter l’assistance",
    contactHint: "Indiquez les versions de l’application et de macOS, le modèle de Mac et si vous utilisez un trackpad ou une souris. Décrivez ce que vous faisiez au moment du problème. N’envoyez pas de mot de passe, de document privé ni de capture contenant des informations personnelles.",
    faqs: [
      { q: "Comment lancer une pause ?", a: "Suivez les étapes proposées à la première ouverture de l’application. Cliquez ensuite sur l’icône en forme de patte dans la barre des menus pour lancer une pause ou ouvrir les réglages." },
      { q: "Quand les rappels apparaissent-ils ?", a: "Choisissez un intervalle de 30, 60 ou 120 minutes. Avec des horaires fixes, un rappel toutes les 30 minutes apparaît à 10 h, 10 h 30, etc. Vous pouvez aussi compter l’intervalle à partir du moment où vous activez les rappels ou les reprenez après une suspension. Vous pouvez aussi définir des plages sans rappels." },
      { q: "Comment caresser le chat ?", a: "Attendez qu’il dorme, puis sélectionnez « Pet the cat » (caresser le chat). Placez le pointeur sur le chat et faites glisser trois doigts sur le trackpad, sans cliquer. Avec une souris, maintenez le bouton enfoncé et faites glisser le pointeur sur le chat." },
      { q: "Pourquoi le geste à trois doigts change-t-il de bureau ?", a: "macOS peut déjà utiliser ce geste pour changer de bureau. Cat Break ne bloque pas les gestes du système et ne modifie pas ces réglages. Utilisez la souris en maintenant le bouton enfoncé, ou vérifiez les réglages des gestes du trackpad dans macOS." },
      { q: "Pourquoi n’y a-t-il pas de son ?", a: "Les sons sont désactivés au départ. Dans les réglages, activez les miaulements ou les ronronnements et augmentez le volume. Le ronronnement commence quand vous caressez le chat endormi. Son volume augmente progressivement jusqu’au niveau choisi et continue tant que vous le caressez." },
      { q: "Comment reprendre mon travail ?", a: "Sélectionnez « Dismiss » pour faire disparaître le chat immédiatement. « Snooze 10 min » le fait aussi disparaître et programme un rappel 10 minutes plus tard. Vous pouvez désactiver ou suspendre les rappels automatiques depuis la barre des menus." },
      { q: "Puis-je désactiver l’animation ?", a: "Oui. Activez « Reduce Motion » dans les réglages pour afficher une image fixe à la place de la vidéo. Cat Break suit également le réglage de réduction des animations de macOS." },
      { q: "Quels sont les Mac et les langues compatibles ?", a: "Cat Break nécessite macOS 15 ou une version ultérieure. L’application propose l’anglais et le coréen. Elle choisit la première de ces langues dans les langues préférées du système, ou l’anglais si aucune n’y figure. Ce site propose aussi le français et le japonais, mais l’application ne prend pas encore ces deux langues en charge." },
      { q: "Où télécharger l’application ?", a: "Cat Break n’est pas encore disponible au public. Sa sortie sur le Mac App Store est en préparation. L’application sera gratuite et ne nécessitera pas de compte." }
    ],
    privacyLabel: "Confidentialité",
    privacyTitle: "Les données de l’app restent sur votre Mac.",
    privacyLead: "Pas de compte, de publicité ni d’outil d’analyse. L’application conserve vos réglages et l’historique des pauses sur votre Mac, sans les envoyer aux serveurs du développeur. Les informations sur les e-mails et l’hébergement du site figurent ci-dessous.",
    privacySections: [
      { title: "Ce que l’application enregistre", body: "L’application enregistre vos réglages et les horaires des rappels. Elle conserve aussi les heures de début et de fin des pauses, leur état, la façon dont elles se terminent et la durée d’affichage du chat. Ces données concernent les pauses dans l’application, pas votre activité professionnelle." },
      { title: "Les gestes de caresse", body: "L’application traite vos gestes pour réagir pendant les caresses. Elle n’enregistre ni les trajectoires des doigts ni les frappes au clavier et ne capture pas l’écran. Elle ne collecte pas le contenu des documents, l’historique de navigation, le son du microphone ni les images de la caméra. Les informations permettant de revenir à l’application précédente restent temporairement en mémoire et ne sont pas enregistrées sur disque." },
      { title: "Supprimer les données de l’application", body: "L’application ne propose pas encore de bouton pour supprimer les réglages ou l’historique des pauses. Pour savoir comment les supprimer, écrivez à music.bk@gmail.com. Supprimer l’application peut laisser certains réglages et enregistrements sur votre Mac." },
      { title: "Les services Apple", body: "Si vous choisissez de partager des diagnostics avec Apple, les politiques d’Apple s’appliquent. Elles couvrent aussi les données traitées par l’App Store et TestFlight, séparément des données que cette application conserve sur votre Mac." },
      { title: "Les e-mails et ce site", body: "Lorsque vous écrivez à l’assistance, vos coordonnées et votre message servent à vous répondre et à résoudre le problème. Vous pouvez demander la suppression de ces échanges à music.bk@gmail.com. Ce site n’utilise ni outil d’analyse ni cookie et n’enregistre pas vos préférences dans le navigateur. Il est hébergé sur GitHub Pages. Les journaux d’accès habituels de l’hébergeur relèvent des politiques de GitHub." }
    ],
    footerLine: "Faites une pause avec un chat.",
    backTop: "Haut de page"
  },
  ko: {
    title: "Cat Break — 고양이와 잠깐 쉬어 가세요.",
    description: "쉴 시간이 되면 화면에 고양이가 찾아와요. 알림 시간을 정하고, 고양이를 쓰다듬고, 원할 때 작업으로 돌아가세요. Mac App Store 출시 준비 중입니다.",
    skip: "본문으로 건너뛰기",
    navHow: "사용 방법",
    navSupport: "지원",
    navPrivacy: "개인정보 보호",
    heroTitle: ["고양이와", "잠깐 쉬어 가세요."],
    heroDescription: "쉴 시간이 되면 화면에 고양이가 찾아와요. 자리를 잡고 잠드는 모습을 지켜보세요. 바쁘다면 언제든 닫고 작업을 이어갈 수 있어요.",
    ctaDemo: "고양이 만나보기",
    ctaSupport: "도움 받기",
    availability: "Mac App Store 출시 준비 중 · macOS 15+ · 무료",
    howLabel: "사용 방법",
    howTitle: ["고양이가 오면,", "잠깐 쉬어 갈 시간."],
    howIntro: "고양이가 찾아올 시간을 정하거나 메뉴 막대에서 직접 불러보세요. 잠깐 함께하다가, 원할 때 작업으로 돌아가면 돼요.",
    steps: [
      { title: "화면 옆에서 걸어와요.", body: "주황 고양이가 화면 가장자리에서 걸어 들어와요. 야옹 소리를 켜 두면, 등장하기 전에 소리로 알려줘요." },
      { title: "잠들면 쓰다듬어 보세요.", body: "고양이가 앉았다가 몸을 눕히고 잠들어요. 잠든 뒤 ‘쓰다듬기’를 누르면 트랙패드나 마우스로 쓰다듬을 수 있어요." },
      { title: "돌아가고 싶을 땐, 바로.", body: "‘닫기’를 누르면 고양이가 바로 사라져요. 조금 뒤에 쉬고 싶다면 ‘10분 뒤’를 눌러주세요. 고양이가 사라지고 10분 뒤에 다시 알려줘요." }
    ],
    galleryLabel: "고양이의 네 가지 모습",
    galleryAlt: [
      "예시 업무 화면 위로 걸어오는 주황 고양이.",
      "예시 업무 화면 앞에 앉아 있는 주황 고양이.",
      "예시 업무 화면 앞에 몸을 눕히는 주황 고양이.",
      "예시 업무 화면 앞에서 잠든 주황 고양이."
    ],
    galleryNames: ["걸어오기", "앉기", "눕기", "잠들기"],
    enlarge: "이미지 크게 보기",
    closeImage: "이미지 닫기",
    detailsLabel: "원하는 대로 설정",
    detailsTitle: ["쉬는 시간도,", "내 방식대로."],
    detailsIntro: "알림 간격은 30분, 60분, 120분 중에서 고를 수 있어요. 알림을 받지 않을 시간을 정하거나, 집중이 필요할 때 잠시 꺼 두세요.",
    features: [
      { title: "기록은 내 Mac에만.", body: "설정과 알림 일정, 휴식 기록은 Mac에 저장해요. 앱은 이 정보를 개발자 서버로 보내지 않아요." },
      { title: "무료로, 가입 없이.", body: "계정을 만들 필요도, 광고를 볼 필요도 없어요. 앱 사용 내역을 추적하는 분석 도구도 사용하지 않아요." },
      { title: "소리는 원할 때만.", body: "야옹과 골골 소리는 처음에는 꺼져 있어요. 각각 켜고 음량을 정할 수 있어요. 골골 소리는 쓰다듬을수록 정해둔 음량까지 커지고, 쓰다듬는 동안 이어져요." }
    ],
    supportLabel: "지원",
    supportTitle: "궁금한 점이 있나요?",
    supportIntro: "자주 묻는 질문을 모았어요. 더 궁금한 점은 이메일로 문의해 주세요.",
    contactLabel: "이메일로 문의하기",
    contactHint: "앱과 macOS 버전, Mac 모델, 트랙패드와 마우스 중 무엇을 쓰는지 알려주세요. 문제가 생겼을 때 어떤 조작을 했는지도 적어주세요. 비밀번호, 개인 문서, 개인정보가 담긴 화면 캡처는 보내지 마세요.",
    faqs: [
      { q: "고양이를 바로 부르려면 어떻게 하나요?", a: "앱을 처음 열 때 나오는 설정 안내를 마쳐주세요. 그다음 메뉴 막대의 발바닥 아이콘을 누르면 휴식을 시작하거나 설정을 열 수 있어요." },
      { q: "알림은 언제 오나요?", a: "30분, 60분, 120분 간격 중에서 선택할 수 있어요. 시계에 맞추면 30분 간격일 때 10시, 10시 30분처럼 정해진 시각에 알려줘요. 알림을 켜거나 잠시 멈췄다가 다시 시작한 때부터 선택한 간격마다 알리는 방식도 있어요. 알림을 받지 않을 시간도 정할 수 있어요." },
      { q: "고양이를 어떻게 쓰다듬나요?", a: "고양이가 잠들면 ‘쓰다듬기’를 눌러주세요. 커서를 고양이 위에 놓고, 클릭하지 않은 채 트랙패드를 세 손가락으로 쓸어주세요. 마우스는 버튼을 누른 채 고양이 위로 움직이면 돼요." },
      { q: "세 손가락으로 쓸면 다른 데스크탑으로 넘어가요.", a: "macOS에 같은 동작이 데스크탑 전환으로 설정되어 있을 수 있어요. Cat Break는 시스템 동작을 막거나 설정을 바꾸지 않아요. 마우스 버튼을 누른 채 움직이는 방법을 쓰거나, macOS의 트랙패드 제스처 설정을 확인해 주세요." },
      { q: "소리가 들리지 않아요.", a: "소리는 처음에는 꺼져 있어요. 설정에서 야옹 또는 골골 소리를 켜고 음량을 높여주세요. 골골 소리는 잠든 고양이를 쓰다듬으면 나기 시작해요. 정해둔 음량까지 점차 커지고, 쓰다듬는 동안 이어져요." },
      { q: "작업으로 돌아가려면 어떻게 하나요?", a: "‘닫기’를 누르면 고양이가 바로 사라져요. ‘10분 뒤’를 누르면 고양이가 사라지고 10분 뒤에 다시 알려줘요. 메뉴 막대에서 자동 알림을 끄거나 잠시 멈출 수도 있어요." },
      { q: "고양이가 움직이지 않게 할 수 있나요?", a: "네. 설정에서 ‘움직임 줄이기’를 켜면 영상 대신 정지 이미지로 보여줘요. macOS의 ‘움직임 줄이기’ 설정도 따라요." },
      { q: "어떤 환경에서 사용할 수 있나요?", a: "macOS 15 이상이 필요해요. 앱은 영어와 한국어를 지원하며, 시스템의 선호 언어 순서에 따라 둘 중 하나를 사용해요. 두 언어가 모두 없으면 영어로 표시해요. 웹사이트는 일본어와 프랑스어도 제공하지만, 앱은 아직 두 언어를 지원하지 않아요." },
      { q: "어디서 다운로드할 수 있나요?", a: "아직 공개 출시 전이에요. Mac App Store 출시를 준비하고 있어요. 무료로 제공하며, 계정 없이 사용할 수 있어요." }
    ],
    privacyLabel: "개인정보 보호",
    privacyTitle: "앱 기록은 Mac 안에.",
    privacyLead: "계정도, 광고도, 분석 도구도 없어요. 앱은 설정과 휴식 기록을 Mac에 저장하고 개발자 서버로 보내지 않아요. 지원 이메일과 웹사이트에서 정보를 다루는 방식은 아래에 안내해요.",
    privacySections: [
      { title: "앱에 저장되는 정보", body: "설정과 알림 일정을 저장해요. 휴식을 시작하고 마친 시각, 진행 상태, 어떻게 종료했는지, 고양이가 표시된 시간도 기록해요. 앱에서의 휴식에 관한 기록이며, 작업 내용을 추적하는 정보는 아니에요." },
      { title: "쓰다듬을 때 사용하는 정보", body: "고양이가 쓰다듬기에 반응하도록 손가락과 마우스 움직임을 일시적으로 처리해요. 손가락이 움직인 경로나 누른 키는 저장하지 않고, 화면을 캡처하지도 않아요. 문서 내용, 웹 방문 내역, 마이크 소리, 카메라 이미지도 수집하지 않아요. 이전 앱으로 돌아가기 위한 정보는 메모리에 잠시 보관하며 파일로 저장하지 않아요." },
      { title: "앱 데이터 삭제", body: "현재 앱에는 설정이나 휴식 기록을 삭제하는 버튼이 없어요. 삭제 방법은 music.bk@gmail.com으로 문의해 주세요. 앱만 지우면 일부 설정과 기록이 Mac에 남을 수 있어요." },
      { title: "Apple 서비스", body: "Apple에 진단 정보를 공유하도록 선택한 경우에는 Apple의 정책이 적용돼요. App Store와 TestFlight가 처리하는 정보에도 Apple의 정책이 적용돼요. 이는 이 앱이 Mac에 저장하는 정보와는 별개예요." },
      { title: "이메일과 웹사이트", body: "이메일로 보내주신 연락처와 문의 내용은 답변과 문제 해결에 사용해요. 문의 내역 삭제는 music.bk@gmail.com으로 요청할 수 있어요. 이 웹사이트는 분석 도구나 쿠키를 사용하지 않고, 브라우저에 환경설정을 저장하지 않아요. 사이트는 GitHub Pages에서 제공해요. 서비스 운영 과정에서 남는 기본 접속 기록에는 GitHub의 정책이 적용돼요." }
    ],
    footerLine: "고양이와 잠깐 쉬어 가세요.",
    backTop: "맨 위로"
  },
  ja: {
    title: "Cat Break — 猫と、ひと休み。",
    description: "休憩の時間になると、画面に猫がやってきます。通知を設定して、猫をなでて、好きな時に作業へ。Mac App Storeでの公開を準備中です。",
    skip: "本文へスキップ",
    navHow: "使い方",
    navSupport: "サポート",
    navPrivacy: "プライバシー",
    heroTitle: ["猫と、", "ひと休み。"],
    heroDescription: "休憩の時間になると、画面に猫がやってきます。くつろいで眠る姿を眺めてみませんか。忙しい時は、いつでも作業に戻れます。",
    ctaDemo: "猫の様子を見る",
    ctaSupport: "ヘルプを見る",
    availability: "Mac App Storeで公開予定 · macOS 15+ · 無料",
    howLabel: "使い方",
    howTitle: ["猫が来たら、", "休憩の時間。"],
    howIntro: "猫が来る時間を決めることも、メニューバーからすぐに呼ぶこともできます。少し休んだら、好きな時に作業へ戻りましょう。",
    steps: [
      { title: "画面の端から、こんにちは。", body: "茶トラの猫が画面の端から歩いてきます。鳴き声をオンにすると、姿を見せる前に声で知らせてくれます。" },
      { title: "眠ったら、なでてみよう。", body: "猫は座ってから横になり、眠りにつきます。眠ったら「Pet the cat」を選ぶと、なでられます。" },
      { title: "いつでも作業に戻れます。", body: "「Dismiss」を選ぶと、猫はすぐに画面から消えます。「Snooze 10 min」なら猫が消え、10分後にもう一度知らせます。" }
    ],
    galleryLabel: "猫の4つのシーン",
    galleryAlt: [
      "作業画面のイメージの上を歩く茶トラの猫。",
      "作業画面のイメージの手前に座る茶トラの猫。",
      "作業画面のイメージの手前で横になる茶トラの猫。",
      "作業画面のイメージの手前で眠る茶トラの猫。"
    ],
    galleryNames: ["歩く", "座る", "横になる", "眠る"],
    enlarge: "画像を拡大",
    closeImage: "画像を閉じる",
    detailsLabel: "お好みの設定で",
    detailsTitle: ["休み方も、", "自分らしく。"],
    detailsIntro: "通知の間隔は30分、60分、120分から選べます。通知しない時間帯を決めたり、集中したい時に一時停止したりすることもできます。",
    features: [
      { title: "記録はMacの中だけに。", body: "設定、通知のスケジュール、休憩の記録はMacに保存します。アプリがこれらを開発者のサーバーに送ることはありません。" },
      { title: "無料。アカウントも不要。", body: "登録は不要で、広告もありません。アプリの利用状況を追跡する解析ツールも使っていません。" },
      { title: "音は、お好みで。", body: "鳴き声とゴロゴロ音は、最初はオフです。それぞれオンにして音量を調整できます。ゴロゴロ音はなでるほど設定した音量まで大きくなり、なでている間は鳴り続けます。" }
    ],
    supportLabel: "サポート",
    supportTitle: "気になることは、こちら。",
    supportIntro: "よくある質問をまとめました。解決しない場合は、メールでお問い合わせください。",
    contactLabel: "メールで問い合わせる",
    contactHint: "アプリとmacOSのバージョン、Macのモデル、トラックパッドとマウスのどちらを使っているかをお知らせください。問題が起きた時の操作もご記入ください。パスワード、個人の文書、個人情報を含むスクリーンショットは送らないでください。",
    faqs: [
      { q: "すぐに休憩を始めるには？", a: "初回起動時の案内に沿って設定を済ませてください。その後、メニューバーの肉球アイコンをクリックすると、休憩を始めたり設定を開いたりできます。" },
      { q: "通知はいつ届きますか？", a: "通知の間隔は30分、60分、120分から選べます。時刻に合わせる場合、30分間隔なら10時、10時30分のように知らせます。もう一つの方法では、通知をオンにした時や一時停止から再開した時を基準に、選んだ間隔で知らせます。通知しない時間帯も指定できます。" },
      { q: "猫をなでるには？", a: "猫が眠ったら「Pet the cat」（なでる）を選びます。ポインタを猫の上に置き、クリックせずに、トラックパッド上で3本の指を滑らせてください。マウスの場合は、ボタンを押したまま猫の上でポインタを動かします。" },
      { q: "3本指でなでるとデスクトップが切り替わります。", a: "macOSで同じジェスチャがデスクトップの切り替えに設定されている場合があります。Cat Breakはシステムのジェスチャを止めたり、設定を変更したりしません。マウスのボタンを押したまま動かす方法を使うか、macOSのトラックパッド設定を確認してください。" },
      { q: "音が聞こえません。", a: "音は最初はオフです。設定で鳴き声やゴロゴロ音をオンにして、音量を上げてください。ゴロゴロ音は眠っている猫をなでると鳴り始めます。設定した音量まで徐々に大きくなり、なでている間は鳴り続けます。" },
      { q: "作業に戻るには？", a: "「Dismiss」を選ぶと、猫はすぐに画面から消えます。「Snooze 10 min」でも猫が消え、10分後にもう一度知らせます。メニューバーから自動通知をオフにしたり、一時停止したりすることもできます。" },
      { q: "アニメーションをオフにできますか？", a: "はい。設定の「Reduce Motion」をオンにすると、動画の代わりに静止画を表示します。macOSの「視差効果を減らす」設定にも従います。" },
      { q: "対応する環境と言語は？", a: "macOS 15以降が必要です。アプリは英語と韓国語に対応しています。システムの優先言語の順に、対応する言語を使います。どちらもない場合は英語で表示します。このウェブサイトには日本語とフランス語もありますが、アプリはまだこの2言語に対応していません。" },
      { q: "どこでダウンロードできますか？", a: "現在、一般公開はしていません。Mac App Storeでの公開を準備中です。無料で、アカウントを作らずに使えます。" }
    ],
    privacyLabel: "プライバシー",
    privacyTitle: "設定と休憩の記録は、Macに保存。",
    privacyLead: "アカウントも、広告も、解析ツールもありません。設定と休憩の記録はMacに保存し、開発者のサーバーには送りません。メールとウェブサイトでの情報の取り扱いは、以下をご確認ください。",
    privacySections: [
      { title: "アプリが保存する情報", body: "設定と通知のスケジュールを保存します。休憩を始めた時刻と終えた時刻、進行状況、終了の仕方、猫が表示されていた時間も記録します。アプリ内の休憩の記録であり、作業内容を追跡するものではありません。" },
      { title: "なでる時に使う情報", body: "猫が反応するために、操作を一時的に処理します。指の動いた軌跡やキー入力は保存せず、画面も撮影しません。文書の内容、閲覧履歴、マイクの音声、カメラの画像も収集しません。前のアプリに戻るための情報は一時的にメモリに保持し、ディスクには保存しません。" },
      { title: "アプリのデータを削除するには", body: "現在、設定や休憩の記録を削除するボタンはありません。削除方法はmusic.bk@gmail.comまでお問い合わせください。アプリを削除するだけでは、一部の設定や記録がMacに残る場合があります。" },
      { title: "Appleのサービス", body: "Appleへの診断情報の共有を選んだ場合は、Appleのポリシーが適用されます。App StoreとTestFlightが扱う情報にもAppleのポリシーが適用されます。これらは、このアプリがMacに保存する情報とは別のものです。" },
      { title: "メールとウェブサイト", body: "メールでいただいた連絡先とお問い合わせ内容は、返信と問題解決に使います。メールのやり取りの削除はmusic.bk@gmail.comまでご依頼ください。このウェブサイトは解析ツールやCookieを使わず、ブラウザに設定を保存しません。サイトはGitHub Pagesで提供しています。サービス運営に伴う標準的なアクセス記録には、GitHubのポリシーが適用されます。" }
    ],
    footerLine: "猫と、ひと休み。",
    backTop: "ページの先頭へ"
  }
};
